[package]
name = "deepterra"
version = "0.1.0"
edition = "2024"

[dependencies]
env_logger = "0.11.8"
futures = "0.3.31"
hcl-rs = "0.19.2"
thiserror = "2.0.12"
tokio = { version = "1.47.0", features = ["rt-multi-thread", "macros", "time"] }
