name: Continuous Development

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        uses: goreleaser/goreleaser-action@v6
        with:
          version: latest
          args: build --clean
      - name: Run tests
        run: cargo test --verbose
