name: Release

on:
  pull_request:
    branches: ["main"]
  push:
    tags:
      - "*"

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Goreleaser
        run: nix develop -c goreleaser release --skip=publish --snapshot --clean
